apiVersion: v1
kind: PersistentVolume
metadata:
  name: kernelci-pv
  namespace: tekton-pipelines
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tekton/kernelci"
