apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kernelci-pvc
  namespace: tekton-pipelines
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
